<h1 style="text-align:center;">
NumPy
</h1>
<p>
◎ In this file, we will learn about the python module/ library "NumPy". It is one of the most useful library for data analysis. NumPy itself does not have a full form in the traditional sense. It refers to "Numerical Python," but it's not an acronym.
</p>

In [30]:
"""
Before learning "NumPy", we should learn an important feature of Python lists. In Python, when we create a variable and store a data in that,
then when we assign that variable to another variable, Python, in the  backend, stores the new variable in a separate memory. So now, we have
two variable with same data which are stored in two separate location. Therefore, if we change one, the other will remain unaffected.
"""
# Example:
a = 56
b = a
b = 30      # Note that, changing the value of b will not affect a.

print(a)
print(b)
print("---" * 5)

"""
But for lists, when we assign the first variable to the second one, both of these variables point to the same data in the same memory location.
So, changing one affects the other.
"""
# Example
x = [i for i in range(10) if i % 2 != 0]        # x = [1, 3, 5, 7, 9]
y = x
y[2] = "---"        # Note that, this assignment will affect both x and y.

print(y)
print(x)
print("---" * 5)

# To make an actual copy of the main list, we can use slicing or the 'copy()' method of lists.
x = [i for i in range(10) if i % 2 != 0]
y = x.copy()        # y = x[:]
y[2] = "---"

print(y)
print(x)

56
30
---------------
[1, 3, '---', 7, 9]
[1, 3, '---', 7, 9]
---------------
[1, 3, '---', 7, 9]
[1, 3, 5, 7, 9]


<p>
◎ You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy "ndarray" class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.
</p>

In [35]:
# Conventional way import NumPy:-
import numpy as np

"""
For 'NumPy' arrays, even the slicing doesn't create a new copy. We have to use the 'copy()' method to make a copy of an array.
"""
d = np.array([i for i in range(10)])
c = d[5:]
c[2] = 69

print(d)
print(c)

[ 0  1  2  3  4  5  6 69  8  9]
[ 5  6 69  8  9]


In [ ]:
"""
In 'NumPy', the word "axis" can take n values for an N-dimensional array. 0 means, the function will be applied row-wise,
and 1 means the function will work column-wise, and so on.
"""

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(a[1,3]) # array_name[row_index, column_index]. Negative index can be used here as well.
print(a[1][3]) # Slicing

# Combination of indexing and slicing:
print(a[:,2::-1])

In [40]:
a = np.ones((2,3,4),dtype='int16')
a
# a.sum(axis=0)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)